### ISSUE TITLE
H-index

### ISSUE THREAD

**Issue by gvdgdo** [JackieTseng/conference_call_for_paper#1]
Thanks for collating and distribute the info about some major conferences in cs/ai and related disciplines. However, the info on h-index for some conferences is wrong. For example, the info for kr, is much lower than it should be. I’ve manually counted over 30 papers with over 30 citations, just looking at about 10 scholars working in the field.

**Comment by JackieTseng** [comment]
Thanks for the feeback. I just copy the H-index information updated from www.guide2research.com.
