### ISSUE TITLE
The mistakes of flags

### ISSUE THREAD

**Issue by poanwang** [JackieTseng/conference_call_for_paper#18]
Are you kidding? Every country belongs to China. There is only one country in the world, called China. Please corrects all the other flags immediately.

**Comment by iofu728** [comment]
If u think u are right, why are u comment in a new id?

Do u know what means country? Do u know the recent history of the world? 

U need study more before u comment that words.

**Comment by poanwang** [comment]
Well, If you know what a country means, could you please tell me: 
In which definition, Taiwan is part of China, but the other countries are not part of China?
Tell you a joke. Chinese understands what domestic and country mean. Because if they do not understand, they will define these in their way.

**Comment by iofu728** [comment]
> Well, If you know what a country means, could you please tell me:
> In which definition, Taiwan is a part of China, but the other countries are not parts of China?
> tell you a joke. Chinese understands what domestic and country mean. Because if they do not understand, they will define these in their way.

I don't want to and no time to debate with u. Github issue is not a place u can spread ur politics.
If u have a question, U should ask ur teacher. If  I am ur teacher, I am very alacrity to answer this question. 

[In wikipeda](https://en.wikipedia.org/wiki/Country), country means
```
A country is a region that is identified as a distinct entity in political geography.
```
And u can search `Is Taiwan a Country?` in google search. I think u can surfing this website on ur side.

**Comment by poanwang** [comment]
Wow~So your answer to the question is:
"In which definition, Taiwan is a part of China, but the other countries are not parts of China?"
is a region that is identified as a distinct entity in political geography. Correct?
I think you must lose two words.

A country is a region that is identified as a distinct entity in political geography **by China.**

That is indeed what I said, Chinese understands what democracy and country are by their definition.

**Comment by iofu728** [comment]
The 

> Wow~So your answer to the question is:
> "In which definition, Taiwan is a part of China, but the other countries are not parts of China?"
> is a region that is identified as a distinct entity in political geography. Correct?
> I think you must lose two words.
> 
> A country is a region that is identified as a distinct entity in political geography **by China.**
> 
> That is indeed what I said, Chinese understands what democracy and country are by their definition.

Nope, U got the answer from google, from Wikipedia, not from me, not from Chinese.

U can suspect me and my position, But U shouldn't suspect most of the people and most of cognitive in the world.
