### ISSUE TITLE
Please state where the h-index values come from

### ISSUE THREAD

**Issue by mhucka** [JackieTseng/conference_call_for_paper#21]
It would be very helpful to know where the h-index values came from. From (closed) issue #1 in this rep, I gather the values came from http://www.guide2research.com. Could the conference page perhaps include a note about this? Even a single footnote would help readers understand the source of the data.

This is a useful page – thank you for putting it together!

**Comment by JackieTseng** [comment]
Thanks for the advice. I have added this comment.
