### ISSUE TITLE
CIKM announaced Important Dates

### ISSUE THREAD

**Issue by YixuanCao** [JackieTseng/conference_call_for_paper#30]
Hi, CIKM has announaced its important dates! 

https://www.cikm2021.org/

Event | Date
-- | --
Workshops Proposal Deadline | 21 Apr 2021
Workshops Notifications | 7 May 2021
Full & Applied Papers Abstract Deadline | 19 May 2021
Full & Applied Papers Final Deadline | 26 May 2021
Short Papers Abstract Deadline | 2 Jun 2021
Short Papers Final Deadline | 9 Jun 2021
Resource & Demo Papers Deadline | 16 Jun 2021
Tutorial Proposals Deadline | 30 Jun 2021
Papers Notifications | 9 Aug 2021
Camera Ready Deadline | 23 Aug 2021

**Comment by JackieTseng** [comment]
Fixed. THX.
