### ISSUE TITLE
Wrong deadlines for CoNLL 2021 and COLING 2022

### ISSUE THREAD

**Issue by tuetschek** [JackieTseng/conference_call_for_paper#32]
AFAIK,
* CoNLL 2021 deadline is 2021-06-14
* COLING 2022 deadline is not known yet -- the conference takes place in October 2022, and there's no deadline on the official website

**Comment by JackieTseng** [comment]
THX, I have updated information about CoNLL. As for COLING 2022, the dates are denoted by *TBD* which means *To Be Decided*. The current deadline is taken from the last COLING as reference. It will be corrected once the conference updates new information.

**Comment by Franck-Dernoncourt** [comment]
> The current deadline is taken from the last COLING as a reference.

For COLING 2022, wrong year: the paper submission deadline should be Jul 1, 202**2** (TBD), not 2021 :)
